apiVersion: skaffold/v2beta25
kind: Config
build:
  artifacts:
  - image: k8s-demo
    buildpacks:
      builder: gcr.io/buildpacks/builder:v1
      env:
      - GOOGLE_RUNTIME_VERSION=17
deploy:
  kubectl: {}
portForward:
- resourceType: service
  resourceName: k8s-demo-svc
  port: 8080
  namespace: default
