apiVersion: v1
kind: Service
metadata:
  name: k8s-demo-svc
  labels:
    app: k8s-demo
spec:
  selector:
    app: k8s-demo
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080